### ISSUE TITLE
附加上手游，碰到错误信息

### ISSUE THREAD

**Issue by 2wong** [axhlzy/Il2CppHookScripts#34]
[Pixel XL::com.xxx.global]-> %resume
[Pixel XL::com.xxx.global]-> TypeError: Cannot read property 'endsWith' of undefined
    at InvocationContext.onLeave (node_modules/frida-il2cpp-bridge/dist/utils/native-wait.js:69:1)
----------------------------------------------------------------------------------------------------                                      
[Pixel XL::com.xxx.global]-> i()                                                                                                          
 --------------------------------------------------------------                                                                           
| List Images { assembly -> image -> classCount -> imageName } |                                                                          
 --------------------------------------------------------------                                                                           
Traceback (most recent call last):                                                                                                        
  File "D:\Anaconda3\envs\f1518\lib\runpy.py", line 194, in _run_module_as_main                                                           
    return _run_code(code, main_globals, None,                                                                                            
  File "D:\Anaconda3\envs\f1518\lib\runpy.py", line 87, in _run_code                                                                      
    exec(code, run_globals)                                                                                                               
  File "D:\Anaconda3\envs\f1518\Scripts\frida.exe\__main__.py", line 7, in <module>                                                       
  File "D:\Anaconda3\envs\f1518\lib\site-packages\frida_tools\repl.py", line 905, in main                                                 
    app.run()                                                                                                                             
  File "D:\Anaconda3\envs\f1518\lib\site-packages\frida_tools\application.py", line 255, in run                                           
    self._reactor.run()                                                                                                                   
  File "D:\Anaconda3\envs\f1518\lib\site-packages\frida_tools\application.py", line 739, in run                                           
    self._run_until_return(self)                                                                                                          
  File "D:\Anaconda3\envs\f1518\lib\site-packages\frida_tools\repl.py", line 349, in _process_input                                       
    if not self._eval_and_print(expression):                                                                                              
  File "D:\Anaconda3\envs\f1518\lib\site-packages\frida_tools\repl.py", line 357, in _eval_and_print                                      
    (t, value) = self._perform_on_reactor_thread(lambda: self._evaluate(expression))                                                      
  File "D:\Anaconda3\envs\f1518\lib\site-packages\frida_tools\application.py", line 572, in _perform_on_reactor_thread                    
    raise error                                                                                                                           
  File "D:\Anaconda3\envs\f1518\lib\site-packages\frida_tools\application.py", line 556, in work                                          
    result[0] = f()                                                                                                                       
  File "D:\Anaconda3\envs\f1518\lib\site-packages\frida_tools\repl.py", line 357, in <lambda>                                             
    (t, value) = self._perform_on_reactor_thread(lambda: self._evaluate(expression))                                                      
  File "D:\Anaconda3\envs\f1518\lib\site-packages\frida_tools\repl.py", line 512, in _evaluate                                            
    raise JavaScriptError(result[1])                                                                                                      
  File "D:\Anaconda3\envs\f1518\lib\site-packages\frida_tools\repl.py", line 910, in __init__                                             
    super(JavaScriptError, self).__init__(error['message'])                                                                               
KeyError: 'message'    

然后就在这卡住不动了，寻求帮助

**Comment by axhlzy** [comment]
frida-il2cpp-bridge 的版本问题，你使用用frida-il2cpp-bridge的新版
他后面新版的变动api变动太大了，我就没跟进了

**Comment by 2wong** [comment]
> frida-il2cpp-bridge 的版本问题，你使用用frida-il2cpp-bridge的新版 他后面新版的变动api变动太大了，我就没跟进了

哦哦  frida-il2cpp-bridge 不好用，目前Il2CppHookScripts哪一版能用啊？
我用master显示il2cpp_assembly_get_image错误，应该是没有导出，这个咋办

**Comment by axhlzy** [comment]
https://github.com/axhlzy/FindIl2cppApi

try
